// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjMpwRM0t1weNvB0lZVxZ3-WLkAff18w8',
    appId: '1:393025467926:web:4d06f9fe9c30b6c932e737',
    messagingSenderId: '393025467926',
    projectId: 'smart-catalog-app-2025',
    authDomain: 'smart-catalog-app-2025.firebaseapp.com',
    storageBucket: 'smart-catalog-app-2025.firebasestorage.app',
    measurementId: 'G-0YNGGK16M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7gh2HMfkCFyij6nASLvHLpOnGo_3K9ck',
    appId: '1:393025467926:android:5a2bf808ba0dc8a232e737',
    messagingSenderId: '393025467926',
    projectId: 'smart-catalog-app-2025',
    storageBucket: 'smart-catalog-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeu77nZhZrlR-yIKBI7MepI8TLmlivM68',
    appId: '1:393025467926:ios:c9d9aab81ff8d68732e737',
    messagingSenderId: '393025467926',
    projectId: 'smart-catalog-app-2025',
    storageBucket: 'smart-catalog-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeu77nZhZrlR-yIKBI7MepI8TLmlivM68',
    appId: '1:393025467926:ios:c9d9aab81ff8d68732e737',
    messagingSenderId: '393025467926',
    projectId: 'smart-catalog-app-2025',
    storageBucket: 'smart-catalog-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBydZVqhtCdQk36J-TX2PNL7FmFx0Ci24U',
    appId: '1:393025467926:web:68cf7ac2b242c10832e737',
    messagingSenderId: '393025467926',
    projectId: 'smart-catalog-app-2025',
    authDomain: 'smart-catalog-app-2025.firebaseapp.com',
    storageBucket: 'smart-catalog-app-2025.firebasestorage.app',
    measurementId: 'G-M12DZY121D',
  );
}
