final List<Map<String, dynamic>> allAppProducts = [
  // --- WOMEN'S FASHION ---
  // Topwear
  {
    'id': 'women_top_001',
    'name': 'Women Solid T-Shirt',
    'brand': 'Highlander',
    'price': 499,
    'originalPrice': 999,
    'discount': 50,
    'rating': 4.3,
    'reviewCount': 1560,
    'category': 'Topwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500&auto=format&fit=crop',
    'quantity': 50,
    'description':
        'A comfortable and stylish solid t-shirt for women. Perfect for casual wear.',
  },
  {
    'id': 'women_top_002',
    'name': 'Essential Logo Crew Sweatshirt',
    'brand': 'Puma',
    'price': 1199,
    'originalPrice': 2999,
    'discount': 60,
    'rating': 4.2,
    'reviewCount': 890,
    'category': 'Topwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1554568218-ffd1e72a2151?w=600&auto=format&fit=crop',
    'quantity': 30,
    'description':
        'Stay warm and stylish with this essential crew neck sweatshirt from Puma.',
  },
  {
    'id': 'women_top_003',
    'name': 'Printed Anarkali Kurta',
    'brand': 'Biba',
    'price': 2499,
    'originalPrice': 4999,
    'discount': 50,
    'rating': 4.4,
    'reviewCount': 3200,
    'category': 'Topwear',
    'gender': 'Women',
    'image':
        'https://media.istockphoto.com/id/1258119410/photo/young-stylish-sexy-woman-in-pajamas-standing-on-terrace-in-tropical-hotel-palm-trees.webp?a=1&b=1&s=612x612&w=0&k=20&c=SOPBPs1BaAQD6bXK_99UJg5GAuHwx_F1vhjq4l9wfns=',
    'quantity': 25,
    'description':
        'Beautifully printed Anarkali kurta, ideal for festive occasions and gatherings.',
  },
  {
    'id': 'women_top_004',
    'name': 'Floral A-Line Dress',
    'brand': 'Only',
    'price': 1799,
    'originalPrice': 3499,
    'discount': 48,
    'rating': 4.3,
    'reviewCount': 1200,
    'category': 'Topwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1618244972963-dbee1a7edc95?w=500&auto=format&fit=crop',
    'quantity': 40,
    'description':
        'Elegant floral A-line dress that brings out your feminine charm.',
  },

  // Bottomwear
  {
    'id': 'women_bottom_001',
    'name': 'Women Slim Fit Jeans',
    'brand': 'Roadster',
    'price': 899,
    'originalPrice': 1499,
    'discount': 40,
    'rating': 4.2,
    'reviewCount': 2400,
    'category': 'Bottomwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&auto=format&fit=crop',
    'quantity': 60,
    'description': 'Classic slim fit jeans that pair well with any top.',
  },
  {
    'id': 'women_bottom_002',
    'name': 'Formal Trousers',
    'brand': 'Marks & Spencer',
    'price': 1999,
    'originalPrice': 2999,
    'discount': 33,
    'rating': 4.1,
    'reviewCount': 850,
    'category': 'Bottomwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1638396637969-956ca903df87?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHdvbWVuJTIwZm9ybWFsJTIwdHJvdXNlcnN8ZW58MHx8MHx8fDA%3D',
    'quantity': 35,
    'description': 'Smart formal trousers for a professional look at work.',
  },
  {
    'id': 'women_bottom_003',
    'name': 'Pleated Midi Skirt',
    'brand': 'Zara',
    'price': 2290,
    'originalPrice': 2290,
    'discount': 0,
    'rating': 4.2,
    'reviewCount': 450,
    'category': 'Bottomwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1706219413873-74517aea8585?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'quantity': 20,
    'description': 'Trendy pleated midi skirt, perfect for a chic day out.',
  },
  {
    'id': 'women_bottom_004',
    'name': 'High-Rise Denim Shorts',
    'brand': 'Levis',
    'price': 1299,
    'originalPrice': 2499,
    'discount': 48,
    'rating': 4.5,
    'reviewCount': 1100,
    'category': 'Bottomwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&auto=format&fit=crop',
    'quantity': 45,
    'description': 'Comfortable high-rise denim shorts for casual summer days.',
  },

  // Footwear
  {
    'id': 'women_foot_001',
    'name': 'Women Heels',
    'brand': 'Catwalk',
    'price': 1995,
    'originalPrice': 3995,
    'discount': 50,
    'rating': 4.5,
    'reviewCount': 1200,
    'category': 'Footwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&auto=format&fit=crop',
    'quantity': 25,
    'description': 'Stylish heels to elevate your fashion statement.',
  },
  {
    'id': 'women_foot_002',
    'name': 'Women Running Shoes',
    'brand': 'Nike',
    'price': 4495,
    'originalPrice': 8995,
    'discount': 50,
    'rating': 4.6,
    'reviewCount': 4100,
    'category': 'Footwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500&auto=format&fit=crop',
    'quantity': 40,
    'description': 'High-performance running shoes for your daily workouts.',
  },
  {
    'id': 'women_foot_003',
    'name': 'Flat Sandals',
    'brand': 'Bata',
    'price': 699,
    'originalPrice': 999,
    'discount': 30,
    'rating': 3.9,
    'reviewCount': 1500,
    'category': 'Footwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=500&auto=format&fit=crop',
    'quantity': 60,
    'description': 'Comfortable flat sandals for everyday wear.',
  },
  {
    'id': 'women_foot_004',
    'name': 'Walking Shoes',
    'brand': 'Skechers',
    'price': 3200,
    'originalPrice': 4500,
    'discount': 28,
    'rating': 4.7,
    'reviewCount': 900,
    'category': 'Footwear',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500&auto=format&fit=crop',
    'quantity': 35,
    'description': 'Lightweight walking shoes designed for maximum comfort.',
  },

  // Accessories
  {
    'id': 'women_acc_001',
    'name': 'Women Watch',
    'brand': 'Titan',
    'price': 4595,
    'originalPrice': 6595,
    'discount': 30,
    'rating': 4.4,
    'reviewCount': 2100,
    'category': 'Accessories',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1657159810148-f6a1f3d74f7e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d29tZW4lMjB3YXRjaGVzfGVufDB8fDB8fHww',
    'quantity': 20,
    'description':
        'Elegant women\'s watch that adds a touch of sophistication.',
  },
  {
    'id': 'women_acc_002',
    'name': 'Textured Handbag',
    'brand': 'Lavie',
    'price': 1299,
    'originalPrice': 3999,
    'discount': 67,
    'rating': 4.0,
    'reviewCount': 5600,
    'category': 'Accessories',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500&auto=format&fit=crop',
    'quantity': 45,
    'description':
        'Spacious and stylish textured handbag for all your essentials.',
  },
  {
    'id': 'women_acc_003',
    'name': 'Aviator Sunglasses',
    'brand': 'Ray-Ban',
    'price': 6590,
    'originalPrice': 8590,
    'discount': 23,
    'rating': 4.7,
    'reviewCount': 980,
    'category': 'Accessories',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&auto=format&fit=crop',
    'quantity': 15,
    'description':
        'Classic aviator sunglasses providing superior UV protection.',
  },
  {
    'id': 'women_acc_004',
    'name': 'Silver Pendant Necklace',
    'brand': 'GIVA',
    'price': 1899,
    'originalPrice': 2500,
    'discount': 24,
    'rating': 4.8,
    'reviewCount': 1500,
    'category': 'Accessories',
    'gender': 'Women',
    'image':
        'https://plus.unsplash.com/premium_photo-1674748384594-47e6b69793fe?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHNpbHZlciUyMG5lY2tsYWNlfGVufDB8fDB8fHww',
    'quantity': 30,
    'description':
        'Delicate silver pendant necklace to complement your neckline.',
  },

  // Grooming
  {
    'id': 'women_groom_001',
    'name': 'Absolute Matte Lipstick',
    'brand': 'Lakme',
    'price': 499,
    'originalPrice': 750,
    'discount': 33,
    'rating': 4.1,
    'reviewCount': 3500,
    'category': 'Grooming',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=500&auto=format&fit=crop',
    'quantity': 100,
    'description': 'Long-lasting matte lipstick for a bold and beautiful look.',
  },
  {
    'id': 'women_groom_002',
    'name': 'Fit Me Foundation',
    'brand': 'Maybelline',
    'price': 599,
    'originalPrice': 799,
    'discount': 25,
    'rating': 4.5,
    'reviewCount': 8900,
    'category': 'Grooming',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500&auto=format&fit=crop',
    'quantity': 80,
    'description':
        'Skin-fitting foundation that provides a natural matte finish.',
  },
  {
    'id': 'women_groom_003',
    'name': 'Paris Hair Serum',
    'brand': 'L\'Oreal',
    'price': 450,
    'originalPrice': 550,
    'discount': 18,
    'rating': 4.4,
    'reviewCount': 6700,
    'category': 'Grooming',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&auto=format&fit=crop',
    'quantity': 70,
    'description': 'Nourishing hair serum for smooth and shiny hair.',
  },
  {
    'id': 'women_groom_004',
    'name': 'Hydro Boost Water Gel',
    'brand': 'Neutrogena',
    'price': 950,
    'originalPrice': 1150,
    'discount': 17,
    'rating': 4.6,
    'reviewCount': 4200,
    'category': 'Grooming',
    'gender': 'Women',
    'image':
        'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=500&auto=format&fit=crop',
    'quantity': 50,
    'description': 'Hydrating water gel that locks in moisture for soft skin.',
  },

  // --- KID'S FASHION ---
  // Topwear
  {
    'id': 'kids_top_001',
    'name': 'Boys Cotton T-Shirt',
    'brand': 'H&M Kids',
    'price': 399,
    'originalPrice': 799,
    'discount': 50,
    'rating': 4.3,
    'reviewCount': 1260,
    'category': 'Topwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=500&auto=format&fit=crop',
    'quantity': 40,
    'description': 'Soft cotton t-shirt for boys, ideal for daily play.',
  },
  {
    'id': 'kids_top_002',
    'name': 'Girls Graphic Sweatshirt',
    'brand': 'GAP Kids',
    'price': 899,
    'originalPrice': 1999,
    'discount': 55,
    'rating': 4.2,
    'reviewCount': 890,
    'category': 'Topwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=500&auto=format&fit=crop',
    'quantity': 35,
    'description':
        'Cute graphic sweatshirt for girls to keep them warm and stylish.',
  },
  {
    'id': 'kids_top_003',
    'name': 'Floral Print Dress',
    'brand': 'Mothercare',
    'price': 1499,
    'originalPrice': 2999,
    'discount': 50,
    'rating': 4.4,
    'reviewCount': 2200,
    'category': 'Topwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=500&auto=format&fit=crop',
    'quantity': 30,
    'description': 'Lovely floral print dress for little fashionistas.',
  },
  {
    'id': 'kids_top_004',
    'name': 'Boys Striped Polo',
    'brand': 'UCB Kids',
    'price': 799,
    'originalPrice': 1599,
    'discount': 50,
    'rating': 4.1,
    'reviewCount': 1100,
    'category': 'Topwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=500&auto=format&fit=crop',
    'quantity': 40,
    'description': 'Classic striped polo shirt for a smart casual look.',
  },

  // Bottomwear
  {
    'id': 'kids_bottom_001',
    'name': 'Boys Slim Fit Jeans',
    'brand': 'Levis Kids',
    'price': 1199,
    'originalPrice': 2199,
    'discount': 45,
    'rating': 4.3,
    'reviewCount': 1800,
    'category': 'Bottomwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=500&auto=format&fit=crop',
    'quantity': 50,
    'description': 'Durable and stylish slim fit jeans for active boys.',
  },
  {
    'id': 'kids_bottom_002',
    'name': 'Girls Cotton Shorts',
    'brand': 'Marks & Spencer',
    'price': 599,
    'originalPrice': 999,
    'discount': 40,
    'rating': 4.0,
    'reviewCount': 750,
    'category': 'Bottomwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500&auto=format&fit=crop',
    'quantity': 45,
    'description': 'Comfortable cotton shorts for girls, perfect for summer.',
  },
  {
    'id': 'kids_bottom_003',
    'name': 'Boys Cargo Pants',
    'brand': 'GAP Kids',
    'price': 1099,
    'originalPrice': 1999,
    'discount': 45,
    'rating': 4.2,
    'reviewCount': 950,
    'category': 'Bottomwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1643641437540-e72c6f3e01c4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8a2lkcyUyMGNhcmdvJTIwcGFudHN8ZW58MHx8MHx8fDA%3D',
    'quantity': 35,
    'description': 'Rugged cargo pants with plenty of pockets for adventures.',
  },
  {
    'id': 'kids_bottom_004',
    'name': 'Girls Denim Skirt',
    'brand': 'Zara Kids',
    'price': 899,
    'originalPrice': 1499,
    'discount': 40,
    'rating': 4.4,
    'reviewCount': 1200,
    'category': 'Bottomwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1503919005314-30d93d07d823?w=500&auto=format&fit=crop',
    'quantity': 30,
    'description': 'Stylish denim skirt that goes well with any top.',
  },

  // Footwear
  {
    'id': 'kids_foot_001',
    'name': 'Kids Sports Shoes',
    'brand': 'Nike Kids',
    'price': 2495,
    'originalPrice': 4995,
    'discount': 50,
    'rating': 4.6,
    'reviewCount': 3100,
    'category': 'Footwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=500&auto=format&fit=crop',
    'quantity': 35,
    'description': 'High-quality sports shoes for energetic kids.',
  },
  {
    'id': 'kids_foot_002',
    'name': 'Boys Running Shoes',
    'brand': 'Puma Kids',
    'price': 1995,
    'originalPrice': 3995,
    'discount': 50,
    'rating': 4.5,
    'reviewCount': 2400,
    'category': 'Footwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=500&auto=format&fit=crop',
    'quantity': 30,
    'description': 'Lightweight running shoes designed for growing feet.',
  },
  {
    'id': 'kids_foot_003',
    'name': 'Kids Clogs',
    'brand': 'Crocs Kids',
    'price': 1299,
    'originalPrice': 2499,
    'discount': 48,
    'rating': 4.2,
    'reviewCount': 1900,
    'category': 'Footwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500&auto=format&fit=crop',
    'quantity': 60,
    'description': 'Easy-to-wear clogs, perfect for indoor and outdoor use.',
  },
  {
    'id': 'kids_foot_004',
    'name': 'School Shoes',
    'brand': 'Bata Kids',
    'price': 899,
    'originalPrice': 1499,
    'discount': 40,
    'rating': 4.0,
    'reviewCount': 2200,
    'category': 'Footwear',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=500&auto=format&fit=crop',
    'quantity': 80,
    'description': 'Durable black school shoes for daily wear.',
  },

  // Accessories
  {
    'id': 'kids_acc_001',
    'name': 'Kids School Bag',
    'brand': 'Skybags',
    'price': 1299,
    'originalPrice': 2499,
    'discount': 48,
    'rating': 4.4,
    'reviewCount': 2800,
    'category': 'Accessories',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&auto=format&fit=crop',
    'quantity': 40,
    'description':
        'Spacious and colourful school bag with multiple compartments.',
  },
  {
    'id': 'kids_acc_002',
    'name': 'Kids Bottle Pack',
    'brand': 'Wildcraft',
    'price': 699,
    'originalPrice': 999,
    'discount': 30,
    'rating': 4.3,
    'reviewCount': 1500,
    'category': 'Accessories',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500&auto=format&fit=crop',
    'quantity': 50,
    'description': 'Durable water bottle pack for school and excursions.',
  },
  {
    'id': 'kids_acc_003',
    'name': 'Kids Sun Cap',
    'brand': 'FabSeasons',
    'price': 299,
    'originalPrice': 599,
    'discount': 50,
    'rating': 4.1,
    'reviewCount': 980,
    'category': 'Accessories',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1604482858862-1db908a653e4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8a2lkcyUyMHdpdGglMjBjYXBzfGVufDB8fDB8fHww',
    'quantity': 45,
    'description': 'Protective and trendy sun cap for outdoor activities.',
  },
  {
    'id': 'kids_acc_004',
    'name': 'Kids Digital Watch',
    'brand': 'Titan Kids',
    'price': 1599,
    'originalPrice': 2599,
    'discount': 38,
    'rating': 4.5,
    'reviewCount': 1800,
    'category': 'Accessories',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=500&auto=format&fit=crop',
    'quantity': 30,
    'description': 'Cool digital watch with rugged design for kids.',
  },

  // Toys
  {
    'id': 'kids_toy_001',
    'name': 'City Building Blocks',
    'brand': 'LEGO',
    'price': 2499,
    'originalPrice': 3999,
    'discount': 37,
    'rating': 4.8,
    'reviewCount': 5600,
    'category': 'Toys',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500&auto=format&fit=crop',
    'quantity': 25,
    'description': 'Creative city building blocks set to unleash imagination.',
  },
  {
    'id': 'kids_toy_002',
    'name': 'Barbie Doll Set',
    'brand': 'Mattel',
    'price': 1299,
    'originalPrice': 1999,
    'discount': 35,
    'rating': 4.6,
    'reviewCount': 4200,
    'category': 'Toys',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500&auto=format&fit=crop',
    'quantity': 40,
    'description': 'Classic Barbie doll set with various accessories.',
  },
  {
    'id': 'kids_toy_003',
    'name': 'Car Track Set',
    'brand': 'Hot Wheels',
    'price': 899,
    'originalPrice': 1499,
    'discount': 40,
    'rating': 4.4,
    'reviewCount': 3100,
    'category': 'Toys',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop',
    'quantity': 35,
    'description': 'Exciting car track set for hours of racing fun.',
  },
  {
    'id': 'kids_toy_004',
    'name': 'Puzzle Game Set',
    'brand': 'Funskool',
    'price': 499,
    'originalPrice': 799,
    'discount': 37,
    'rating': 4.2,
    'reviewCount': 1900,
    'category': 'Toys',
    'gender': 'Kids',
    'image':
        'https://images.unsplash.com/photo-1530325553241-4f6e7690cf36?w=500&auto=format&fit=crop',
    'quantity': 60,
    'description': 'Educational puzzle game set to challenge young minds.',
  },

  // --- MEN'S FASHION ---
  // Topwear
  {
    'id': 'men_top_001',
    'name': 'Men Typography Printed T-Shirt',
    'brand': 'Roadster',
    'price': 499,
    'originalPrice': 1499,
    'discount': 67,
    'rating': 4.3,
    'reviewCount': 2100,
    'category': 'Topwear',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&auto=format&fit=crop',
    'quantity': 50,
    'description': 'Casual comfort with a trendy typography print.',
  },
  {
    'id': 'men_top_002',
    'name': 'Men Slim Fit Casual Shirt',
    'brand': 'HIGHLANDER',
    'price': 699,
    'originalPrice': 1999,
    'discount': 65,
    'rating': 4.1,
    'reviewCount': 1800,
    'category': 'Topwear',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&auto=format&fit=crop',
    'quantity': 45,
    'description':
        'Sharp slim fit casual shirt suitable for various occasions.',
  },
  {
    'id': 'men_top_003',
    'name': 'Men Solid Bomber Jacket',
    'brand': 'WROGN',
    'price': 1299,
    'originalPrice': 3999,
    'discount': 68,
    'rating': 4.2,
    'reviewCount': 980,
    'category': 'Topwear',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&auto=format&fit=crop',
    'quantity': 30,
    'description': 'Stylish solid bomber jacket to layer up your outfit.',
  },
  {
    'id': 'men_top_004',
    'name': 'Rapid Dry Training T-Shirt',
    'brand': 'HRX',
    'price': 599,
    'originalPrice': 1299,
    'discount': 54,
    'rating': 4.4,
    'reviewCount': 2800,
    'category': 'Topwear',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500&auto=format&fit=crop',
    'quantity': 55,
    'description':
        'Moisture-wicking training t-shirt for your intense workouts.',
  },
  {
    'id': 'men_top_005',
    'name': 'Essential Logo Crew Sweatshirt',
    'brand': 'Puma',
    'price': 1199,
    'originalPrice': 2999,
    'discount': 60,
    'rating': 4.2,
    'reviewCount': 890,
    'category': 'Topwear',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1554568218-ffd1e72a2151?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHN3ZWF0c2hpcnR8ZW58MHx8MHx8fDA%3D',
    'quantity': 35,
    'description': 'Timeless crew neck sweatshirt with the iconic Puma logo.',
  },
  {
    'id': 'men_top_006',
    'name': 'Men Cotton Sweater',
    'brand': 'U.S. Polo Assn.',
    'price': 1899,
    'originalPrice': 3299,
    'discount': 42,
    'rating': 4.3,
    'reviewCount': 1800,
    'category': 'Topwear',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500&auto=format&fit=crop',
    'quantity': 25,
    'description': 'Soft cotton sweater for a sophisticated winter look.',
  },
  {
    'id': 'men_ethnic_001', // Ethnic can be under Topwear or separate
    'name': 'Men Kurta Set',
    'brand': 'Manyavar',
    'price': 3999,
    'originalPrice': 5999,
    'discount': 33,
    'rating': 4.6,
    'reviewCount': 2400,
    'category': 'Ethnic',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1727835523545-70ee992b5763?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWVucyUyMGt1cnRhfGVufDB8fDB8fHww',
    'quantity': 20,
    'description': 'Traditional kurta set perfect for weddings and festivals.',
  },

  // Bottomwear
  {
    'id': 'men_bottom_001',
    'name': '511 Slim Fit Jeans',
    'brand': 'Levis',
    'price': 1799,
    'originalPrice': 3999,
    'discount': 55,
    'rating': 4.5,
    'reviewCount': 3200,
    'category': 'Bottomwear',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&auto=format&fit=crop',
    'quantity': 45,
    'description': 'The definitive slim fit jean, giving a modern look.',
  },
  {
    'id': 'men_bottom_002',
    'name': 'Men Slim Fit Chinos',
    'brand': 'Jack & Jones',
    'price': 1499,
    'originalPrice': 2999,
    'discount': 50,
    'rating': 4.3,
    'reviewCount': 1560,
    'category': 'Bottomwear',
    'gender': 'Men',
    'image':
        'https://media.istockphoto.com/id/692909922/photo/hes-off-on-an-adventure.webp?a=1&b=1&s=612x612&w=0&k=20&c=d-bqdMaEQakXXATRVAAy9EhXDm0zSsiAKevpLlkuKBE=',
    'quantity': 40,
    'description': 'Versatile slim fit chinos for smart-casual styling.',
  },

  // Footwear
  {
    'id': 'men_foot_001',
    'name': 'Air Max 270 Running Shoes',
    'brand': 'Nike',
    'price': 8995,
    'originalPrice': 12995,
    'discount': 31,
    'rating': 4.6,
    'reviewCount': 4500,
    'category': 'Footwear',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop',
    'quantity': 25,
    'description': 'Iconic Air Max comfort with a bold look.',
  },
  {
    'id': 'men_foot_002',
    'name': 'Ultraboost 21',
    'brand': 'Adidas',
    'price': 14999,
    'originalPrice': 17999,
    'discount': 17,
    'rating': 4.8,
    'reviewCount': 3200,
    'category': 'Footwear',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500&auto=format&fit=crop',
    'quantity': 20,
    'description': 'Ultimate energy return with every stride.',
  },
  {
    'id': 'men_foot_003',
    'name': 'RS-X Reinvention',
    'brand': 'Puma',
    'price': 8999,
    'originalPrice': 9999,
    'discount': 10,
    'rating': 4.5,
    'reviewCount': 1500,
    'category': 'Footwear',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500&auto=format&fit=crop',
    'quantity': 25,
    'description': 'Retro-future design for street style enthusiasts.',
  },

  // Accessories
  {
    'id': 'men_acc_001',
    'name': 'Men Leather Watch',
    'brand': 'Fossil',
    'price': 5995,
    'originalPrice': 8995,
    'discount': 33,
    'rating': 4.5,
    'reviewCount': 1200,
    'category': 'Accessories',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=500&auto=format&fit=crop',
    'quantity': 15,
    'description': 'Classic leather watch that stands the test of time.',
  },
  {
    'id': 'men_acc_002',
    'name': 'Neo Men Leather Watch',
    'brand': 'Titan',
    'price': 4595,
    'originalPrice': 6595,
    'discount': 30,
    'rating': 4.4,
    'reviewCount': 2100,
    'category': 'Accessories',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1627094522148-ac0c843a1383?w=500&auto=format&fit=crop',
    'quantity': 20,
    'description': 'Sophisticated timepiece for the modern man.',
  },
  {
    'id': 'men_acc_003',
    'name': 'Aviator Sunglasses',
    'brand': 'Ray-Ban',
    'price': 8590,
    'originalPrice': 10590,
    'discount': 19,
    'rating': 4.7,
    'reviewCount': 4100,
    'category': 'Accessories',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&auto=format&fit=crop',
    'quantity': 15,
    'description': 'Timeless aviator shades for a cool look.',
  },

  // Grooming
  {
    'id': 'men_groom_001',
    'name': 'Beard Growth Oil',
    'brand': 'Beardo',
    'price': 499,
    'originalPrice': 750,
    'discount': 33,
    'rating': 4.1,
    'reviewCount': 3500,
    'category': 'Grooming',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=500&auto=format&fit=crop',
    'quantity': 50,
    'description': 'Nurture your beard with this growth promoting oil.',
  },
  {
    'id': 'men_groom_002',
    'name': 'Charcoal Face Wash',
    'brand': 'The Man Company',
    'price': 299,
    'originalPrice': 349,
    'discount': 14,
    'rating': 4.2,
    'reviewCount': 5600,
    'category': 'Grooming',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1559563458-527698bf5295?w=500&auto=format&fit=crop',
    'quantity': 60,
    'description': 'Deep cleanse your skin with activated charcoal.',
  },
  {
    'id': 'men_groom_003',
    'name': 'Shaving Kit',
    'brand': 'Bombay Shaving Co.',
    'price': 1299,
    'originalPrice': 1999,
    'discount': 35,
    'rating': 4.4,
    'reviewCount': 1200,
    'category': 'Grooming',
    'gender': 'Men',
    'image':
        'https://images.unsplash.com/photo-1621607512214-68297480165e?w=500&auto=format&fit=crop',
    'quantity': 25,
    'description': 'Complete shaving kit for a premium grooming experience.',
  },

  // --- HOME SCREEN FEATURED ---
  {
    'id': 'Nike_Shoe_001',
    'name': 'Nike Air Max',
    'brand': 'Nike',
    'price': 4995,
    'originalPrice': 8995,
    'discount': 45,
    'rating': 4.5,
    'reviewCount': 2400, // Converted from '2.4k'
    'category': 'Footwear',
    'gender': 'Unisex',
    'image':
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop',
    'quantity': 30,
    'description': 'Classic Air Max cushioning for all-day comfort.',
  },
  {
    'id': 'Adidas_Shoe_002',
    'name': 'Adidas Ultraboost',
    'brand': 'Adidas',
    'price': 6500,
    'originalPrice': 12000,
    'discount': 46,
    'rating': 4.7,
    'reviewCount': 1800, // Converted from '1.8k'
    'category': 'Footwear',
    'gender': 'Unisex',
    'image':
        'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&auto=format&fit=crop',
    'quantity': 25,
    'description': 'High-performance running shoes.',
  },
  {
    'id': 'Puma_Shoe_003',
    'name': 'Puma RS-X',
    'brand': 'Puma',
    'price': 3999,
    'originalPrice': 7999,
    'discount': 50,
    'rating': 4.3,
    'reviewCount': 950,
    'category': 'Footwear',
    'gender': 'Unisex',
    'image':
        'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop',
    'quantity': 35,
    'description': 'Stylish sneakers for casual outings.',
  },
  {
    'id': 'Reebok_Shoe_004',
    'name': 'Reebok Classic',
    'brand': 'Reebok',
    'price': 2499,
    'originalPrice': 4999,
    'discount': 50,
    'rating': 4.2,
    'reviewCount': 1200, // Converted from '1.2k'
    'category': 'Footwear',
    'gender': 'Unisex',
    'image':
        'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop',
    'quantity': 40,
    'description': 'Timeless classic design for everyday comfort.',
  },
  {
    'id': 'UnderArmour_Shoe_005',
    'name': 'Under Armour',
    'brand': 'Under Armour',
    'price': 5500,
    'originalPrice': 8000,
    'discount': 30,
    'rating': 4.6,
    'reviewCount': 500,
    'category': 'Footwear',
    'gender': 'Unisex',
    'image':
        'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop',
    'quantity': 20,
    'description': 'Sport style shoes for training and casual wear.',
  },
  {
    'id': 'Skechers_Shoe_006',
    'name': 'Skechers GoWalk',
    'brand': 'Skechers',
    'price': 2999,
    'originalPrice': 4500,
    'discount': 33,
    'rating': 4.4,
    'reviewCount': 3100, // Converted from '3.1k'
    'category': 'Footwear',
    'gender': 'Unisex',
    'image':
        'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop',
    'quantity': 45,
    'description': 'Designed for walking comfort.',
  },
];
