type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  shippingAddress: String
  billingAddress: String
}

type Category @table {
  name: String!
  createdAt: Timestamp!
  description: String
}

type Product @table {
  name: String!
  price: Float!
  description: String!
  category: Category!
  createdAt: Timestamp!
  imageUrl: String
  stockQuantity: Int
}

type CartItem @table {
  user: User!
  product: Product!
  quantity: Int!
  createdAt: Timestamp!
}

type Order @table {
  user: User!
  orderDate: Timestamp!
  totalAmount: Float!
  status: String!
  createdAt: Timestamp!
  shippingAddress: String
}

type OrderItem @table {
  order: Order!
  product: Product!
  quantity: Int!
  unitPrice: Float!
}